### ISSUE TITLE
Version 2.0 rewrite

### ISSUE THREAD

**Issue by modev** [astra137/node-mojang#10]
The last weeks developing with this wrapper made me feel like communication requires a lot of workarounds. For example, when I'm doing a request with invalid user credentials I'd expect the promise to be rejected instead of being resolved with an error. The same unexpected behaviour is seen when using functions which return an empty payload if they were successful (like I mentioned in #5). 
As @jamen already said some code optimizations #9 like would be useful as well. 
I feel like implementing this into a new complete 2.0 rewrite would be more effective than using the existing codebase. I have some ideas for the rewrite and I'd like to hear your opinion on this.

- Test Coverage as high as possible (goal is 100%). __Coveralls + Travis__?
- Enforcing a consistent code style. __[Standard](https://standardjs.com/)__?
- Interactive API Documentation for the Mojang API. __[Swagger UI](http://swagger.io/swagger-ui/)__?
- ES6 features (Babel) vs. standard node runtime features? 

I'd love to hear your opinion and if anybody would be willing to help me.

**Comment by dscalzi** [comment]
I'd be willing to help, but I haven't been developing javascript for very long (about two months). I'd love to learn more widely used development conventions and integrations. This could help to that end, since it's not really a terribly complicated task.

**Comment by astra137** [comment]
I would love to help! I have been developing an Electron-wrapped modpack launcher and naively wrote my own Yggdrasil client. I have a preference for `got` and `xo` styling, but I am more interested in following a repo's given guidelines.

**Comment by jamen** [comment]
@maccelerated Great! I sent an invite.

Just a reminder: I designed this a while back, and my style has changed since then.  I don't plan on maintaining this too heavily, so feel free to change this however once we can reach some consensus.

Here are my opinions:

 - Test coverage is good, no doubt
 - I like `standard` code style, it has influenced how I write JS today
 - Interactive code sounds interesting, but would be best to put on hold.
 - I never setup Babel for libraries like this one because it feels like a hassle.

If we are going to release a major version, we should think about the lessons learned from using this library.

 - As mentioned: Promises aren't resolving/rejecting as expected.
 - The function interfaces accept a lot of variation on input which might not be necessary.
 - The functions can be implemented better.
 - There is possibly more functions that could be implemented.
 - Can we make this package more known?  Adding links to wikis for example
 - Should this be designed more suitable for browser?
   - A better request library
   - Bundles better

Just some food for thought.  :smile:

**Comment by astra137** [comment]
My immediate feedback is that test coverage is high priority, `standard` is a great choice, I vote that npm packages should avoid transpiling unless absolutely necessarily and instead just target a sane Node version, and I'll take a peek at the current promise resolutions on the endpoints to see what makes sense and what doesn't when I have time. I'm always happy to talk things out and thank you for the invite!

**Comment by astra137** [comment]
Okay, so I went a bit ham.

https://github.com/maccelerated/node-mojang
https://maccelerated.github.io/node-mojang/

**Comment by jamen** [comment]
@maccelerated Looks awesome! Please open a PR for review.   Also would you want to transfer this to your account (or some org) after PR is settled?

**Comment by astra137** [comment]
I made [an org for some other MC-related stuff I was up to](https://github.com/crafting-table), but it doesn't really matter to me either way. Honestly, it's probably better OSS practice for me to learn how to branch and do PRs on someone else's repo.

**Comment by dscalzi** [comment]
Resolved by #13
