### ISSUE TITLE
Resolve security issue with hoek

### ISSUE THREAD

**Issue by astra137** [astra137/node-mojang#20]
CVE-2018-3728
recommended: hoek ~> 5.0.3

**Comment by dscalzi** [comment]
Codecov requires Request,
Request requires Hawk,
Hawk requires hoek

More information on the issue can be found on this issue, https://github.com/request/request/issues/2926.

Updating codecov will the resolve issue. Hoek 4.2.1 is patched and the latest Codecov has that version.

Change https://github.com/maccelerated/node-mojang/blob/master/package.json#L29 to version 3.0.1

Might require a semver-patch release so that dependents arent affected.

**Comment by JessicaSachs** [comment]
[Here's Github's response.](https://github.com/hapijs/hoek/issues/247#issuecomment-386708295) TL;DR: they've gone through and deleted the bad alerts, and promised to be better about validating if security vulnerabilities are legit before putting alerts out. Looks like you shouldn't need to do anything :-)

**Comment by dscalzi** [comment]
It needs to be resolved, 4.2.1+ is patched. We are not on that version.
https://github.com/maccelerated/node-mojang/blob/master/package-lock.json#L4027

Edit: I'll patch master, I'll leave it up to you to merge it into the feature branches. There should be no merge conflicts as it's simply changing codecov's version.

**Comment by dscalzi** [comment]
Fixed https://github.com/maccelerated/node-mojang/commit/ac450708b58bcfea283b1ea5f72754db2ecb35b5
