### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by jamen** [astra137/node-mojang#8]
Something I considered a while back, but never ended up doing, was a client API where tokens are stored and used in subsequent requests:

```js
const client = mojang.client({ user, pass, ... })

// Create and store token
await client.login()

// Make request that require a token
let valid = await client.validate()
let info = await client.user()
// skin requests?
// ...
```

To be honest I made the current API a while back as a very barebones way to wrap the requests.   Things can redone/added if you want a more high-level wrapping of their API.

**Comment by modev** [comment]
I think redoing some parts of the API would make sense. For example it would make sense if Mojang-API errors would reject the promise instead of resolving it with a JSON object.
Making a object oriented version of the API would be great for client side apps, but the current design is really good for server side use!

**Comment by astra137** [comment]
The OO approach might be useful for ephemeral work like command line apps or something. I found that in making a GUI client, I just stored the session and client token to JSON file or app state object and read the state whenever I needed them.
